### ISSUE TITLE
Convert Angular App to PWA

### ISSUE THREAD

**Issue by vdias38** [devizem/Eventure#31]
Below few links to understand what PWA is and how to convert our Angular app to PWA:

- [What's a PWA](https://meumobi.github.io/pwa/2017/12/28/getting-started-progressive-web-app.html)
- [How to convert an Angular app to PWA](https://medium.com/ngconf/angular-pwa-install-and-configure-858dd8e9fb07)
- [Adaptive icon support in PWAs with maskable icons](https://web.dev/maskable-icon/)

**Comment by SirZemar** [comment]
<h3>Add @angular/pwa package</h3>

```sh
root$ ng add @angular/pwa
```

 <h3>Run the application locally.</h3>

```sh
root$ ng build --configuration production
root/www$ http-server
```

Error: many modules aren't being found and service worker isn't active.
All packages were installed successfuly and the distribution folder installed all files correctly.

<img width="1280" alt="Screenshot 2022-05-11 at 16 54 21" src="https://user-images.githubusercontent.com/87383586/167900032-8aa81102-33f4-4567-bf23-e3e02cfcc1a2.png">

<img width="1280" alt="Screenshot 2022-05-11 at 17 06 18" src="https://user-images.githubusercontent.com/87383586/167900447-96b53d6b-6090-4c8e-9db0-02dd6ec8b8c8.png">
