### ISSUE TITLE
Remove ionic schematics

### ISSUE THREAD

**Issue by vdias38** [devizem/Eventure#5]
see DOCS/SETUP for more details

**Comment by SirZemar** [comment]
Missing ionic modules import when generating module and html ionic ready

**Comment by vdias38** [comment]
Not sure if I understand your comment but this behaviour seems to be discussed on [doc](/devizem/Eventure/blob/main/docs/SETUP.md#make-ng-components-ionic-compliant):

> - When create module imports IonicModule
> - When create component update html to include ion-content

**Comment by SirZemar** [comment]
Exactly those two steps in "Make ng components Ionic compliant". I was unsure if they are meant to be done manually after each component/module generate or automatically.
